
# .goreleaser.yml
version: 2
project_name: k20s

builds:
  - id: k20s
    main: ./cmd/main.go
    binary: manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k20s:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/k20s:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    ids:
      - k20s

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
