apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: k20s
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/opscalehub/k20s
    context: .
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - config/default
